### PR TITLE
[Need testing] [Hopefully] Prevent "No such interface supported"

### PR DESCRIPTION
**Pull request by ray1997**
By checking if file is locally provided on computer, otherwise, ask cached manager to complete update on it right away????

Need confirming if this will solve #215 or not

Edit1: Beware that test saving same file over and over the result eventually never showed up again, until testing on other file as I tried testing on saving 🤨 emoji, error pop up on SVG save, then saving on PNG no error show up. Until saving other emoji on PNG first and error eventually showed up

Edit2: Previous codes test on on no-interface branch, as I am now testing on latest release version. Saving file on OneDrive show the error and saving on local folder show successfully saved the icon

### CODE REVIEW

**Comment by JohnnyWestlake** [comment]
This is strange as the CachedFileManager is only really important for OneDrive files in the first place. If it's stopped working (probably some OS update?) may as well remove the CachedFileManager calls entirely 🤔

**Comment by ray1997** [comment]
I tried removed that code entirely, and the error is vanished! But I'm worry what will happen on older version of Windows...

**Comment by ray1997** [comment]
Test on Windows 10 version 19042 21H2 saving 🍦📿 and a few random emojis as colored glyph
- Save as SVG on OneDrive
- Save as SVG on Desktop
- Save as PNG on OneDrive
- Save as PNG on Desktop

None of these configurations throw error of no supported interface.

**Review by JohnnyWestlake — CHANGES_REQUESTED** [review]
Probably we should remove the two `await CachedFileManager.CompleteUpdatesAsync(file);` towards the end of those methods too, just in case.

**Review by JohnnyWestlake — APPROVED** [review]

**Pull request merged**
